import { v } from "convex/values";
const curvePolicyValidator = v.union(v.object({ mode: v.literal("fixed"), value: v.number() }), v.object({ mode: v.literal("linear"), from: v.number(), to: v.number() }), v.object({
    mode: v.literal("step"),
    start: v.number(),
    increment: v.number(),
    cap: v.optional(v.number()),
}), v.object({
    mode: v.literal("randomRange"),
    min: v.number(),
    max: v.number(),
    seedMode: v.optional(v.union(v.literal("session"), v.literal("level"))),
}));
const budgetPolicyValidator = v.object({
    mode: v.literal("budget"),
    count: v.number(),
    distribution: v.union(v.literal("even"), v.literal("random"), v.literal("early"), v.literal("late"), v.literal("manual")),
    levels: v.optional(v.array(v.number())),
});
export const levelBandPolicyValidator = v.object({
    id: v.string(),
    fromLevel: v.number(),
    toLevel: v.number(),
    asteroidCount: curvePolicyValidator,
    asteroidSpeed: curvePolicyValidator,
    shipPickups: budgetPolicyValidator,
    powerups: budgetPolicyValidator,
    maxLives: curvePolicyValidator,
    chaos: v.optional(v.object({ enabled: v.boolean() })),
});
export const progressionBandsValidator = v.array(levelBandPolicyValidator);
export const REQUIRED_GAME_CONFIG_FIELDS = {
    applyToRunning: v.boolean(),
    powerupSpawnDelayMs: v.number(),
    shipPickupSpawnDelayMs: v.number(),
    maxPowerupsOnScreen: v.number(),
    powerupDurationMs: v.number(),
    maxLives: v.number(),
    startingLives: v.number(),
    shipRadius: v.number(),
    shipRotationSpeed: v.number(),
    shipAcceleration: v.number(),
    shipInertia: v.number(),
    shipInvulnerabilityMs: v.number(),
    normalBulletSpeed: v.number(),
    rapidBulletSpeed: v.number(),
    normalFireDelayMs: v.number(),
    rapidFireDelayMs: v.number(),
    bulletRadius: v.number(),
    rapidBulletRadius: v.number(),
    rapidBulletPower: v.number(),
    bulletCollisionPadding: v.number(),
    largeAsteroidRadius: v.number(),
    mediumAsteroidRadius: v.number(),
    smallAsteroidRadius: v.number(),
    asteroidVelocityMin: v.number(),
    asteroidVelocityMax: v.number(),
    asteroidScoreLarge: v.number(),
    asteroidScoreMedium: v.number(),
    asteroidScoreSmall: v.number(),
    pillSpawnDelayMs: v.number(),
    tokenSpawnDelayMs: v.number(),
    spaceTokenSpawnChance: v.number(),
    pickupTtlMs: v.number(),
    pickupRadius: v.number(),
    shipPickupRadius: v.number(),
    maxShipPickupsOnScreen: v.number(),
    progressionBands: progressionBandsValidator,
    quarterUsd: v.number(),
    tierBreakpointsUsd: v.array(v.number()),
    pillsPerTier: v.array(v.number()),
    astrdsPerPill: v.array(v.number()),
};
export const GAME_CONFIG_TABLE_FIELDS = {
    version: v.number(),
    applyToRunning: v.boolean(),
    powerupSpawnDelayMs: v.number(),
    shipPickupSpawnDelayMs: v.number(),
    maxPowerupsOnScreen: v.number(),
    powerupDurationMs: v.number(),
    maxLives: v.number(),
    startingLives: v.optional(v.number()),
    shipRadius: v.optional(v.number()),
    shipRotationSpeed: v.optional(v.number()),
    shipAcceleration: v.optional(v.number()),
    shipInertia: v.optional(v.number()),
    shipInvulnerabilityMs: v.optional(v.number()),
    normalBulletSpeed: v.optional(v.number()),
    rapidBulletSpeed: v.optional(v.number()),
    normalFireDelayMs: v.optional(v.number()),
    rapidFireDelayMs: v.optional(v.number()),
    bulletRadius: v.optional(v.number()),
    rapidBulletRadius: v.optional(v.number()),
    rapidBulletPower: v.optional(v.number()),
    bulletCollisionPadding: v.optional(v.number()),
    largeAsteroidRadius: v.optional(v.number()),
    mediumAsteroidRadius: v.optional(v.number()),
    smallAsteroidRadius: v.optional(v.number()),
    asteroidVelocityMin: v.optional(v.number()),
    asteroidVelocityMax: v.optional(v.number()),
    asteroidScoreLarge: v.optional(v.number()),
    asteroidScoreMedium: v.optional(v.number()),
    asteroidScoreSmall: v.optional(v.number()),
    pillSpawnDelayMs: v.optional(v.number()),
    tokenSpawnDelayMs: v.optional(v.number()),
    spaceTokenSpawnChance: v.optional(v.number()),
    pickupTtlMs: v.optional(v.number()),
    pickupRadius: v.optional(v.number()),
    shipPickupRadius: v.optional(v.number()),
    maxShipPickupsOnScreen: v.optional(v.number()),
    progressionBands: v.optional(progressionBandsValidator),
    quarterUsd: v.optional(v.number()),
    tierBreakpointsUsd: v.optional(v.array(v.number())),
    pillsPerTier: v.optional(v.array(v.number())),
    astrdsPerPill: v.optional(v.array(v.number())),
};
