[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
space_vault_program = "4bRZK8XfziVhLCgvtRdFJyTgN6tXGSPJT8xfbtt1AxBB"
earth_vault_program = "J3jkrtAqnr7Vs6evka3wdugjdagwUJhGj3Mzae6wdABB"

[programs.localnet]
space_vault_program = "4bRZK8XfziVhLCgvtRdFJyTgN6tXGSPJT8xfbtt1AxBB"
earth_vault_program = "J3jkrtAqnr7Vs6evka3wdugjdagwUJhGj3Mzae6wdABB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
bind_address = "127.0.0.1"

[[test.validator.account]]
address = "5sqKSHDKZr4KbNzj972PSfmEhtR9eLeBvv1nBRbeQAnB"
filename = "tests/fixtures/astrds-mint-account.json"

[scripts]
test = "npx ts-mocha --esm -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
