[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@supabase/supabase-js"]

[build.environment]
NODE_VERSION = "18"
