// config/seedData.ts - Initial world setup data

// Location seed data
export const LOCATION_SEED_DATA = [
  {
    id: 'mining-plains',
    name: 'Mining Plains',
    description: 'Rich in basic materials and perfect for newcomers',
    svgpathid: 'mining-plains-path',
    theme: 'plains',
    biome: 'plains',
    difficulty: 1,
    locationType: 'REGION',
    hasMarket: true,
    hasMining: true,
    hasTravel: true,
    hasChat: true,
    chatScope: 'LOCAL',
    welcomeMessage: 'The wind carries the sound of pickaxes striking stone.',
    lore: 'Once a vast battlefield, these plains now serve as the primary mining grounds for new arrivals.',
    mapX: 100,
    mapY: 200,
  },
  {
    id: 'crystal-caves',
    name: 'Crystal Caves',
    description: 'Deep underground shafts where rare crystals grow',
    svgpathid: 'underland-island',
    theme: 'underground',
    biome: 'underground',
    difficulty: 2,
    locationType: 'REGION',
    hasMarket: true,
    hasMining: true,
    hasTravel: true,
    hasChat: true,
    chatScope: 'LOCAL',
    welcomeMessage: 'Crystalline formations sparkle in your torchlight.',
    lore: 'Ancient mineral deposits form geometric patterns that seem almost intentional.',
  },
  {
    id: 'underland',
    name: 'Underland',
    description: 'Vast red-earth territories where ancient songlines whisper',
    svgpathid: 'underland',
    theme: 'wilderness',
    biome: 'wilderness',
    difficulty: 3,
    locationType: 'REGION',
    hasMarket: true,
    hasMining: true,
    hasTravel: true,
    hasChat: true,
    chatScope: 'LOCAL',
    welcomeMessage:
      'The red earth stretches endlessly under the scorching sun.',
    lore: 'These ancient lands hold secrets older than memory, where the very stones seem to hum with stories.',
  },
  {
    id: 'fungi-networks',
    name: 'Fungi Networks',
    description: 'Underground mycelium city where everything is connected',
    svgpathid: 'fungi-networks',
    theme: 'underground',
    biome: 'underground',
    difficulty: 3,
    locationType: 'REGION',
    hasMarket: true,
    hasMining: true,
    hasTravel: true,
    hasChat: true,
    chatScope: 'LOCAL',
    welcomeMessage: 'The network acknowledges your presence.',
    lore: 'A vast underground organism that has achieved collective consciousness.',
  },
  {
    id: 'frostpine-reaches',
    name: 'Frostpine Reaches',
    description: 'Snow-covered wilderness where old stories still echo',
    svgpathid: 'frostpine-reaches',
    theme: 'alpine',
    biome: 'alpine',
    difficulty: 3,
    locationType: 'REGION',
    hasMarket: true,
    hasMining: true,
    hasTravel: true,
    hasChat: true,
    chatScope: 'LOCAL',
    welcomeMessage:
      'The silence here is broken only by wind through ancient pines.',
    lore: 'Local hunters speak in hushed tones of tracks too large for any known beast.',
  },
  {
    id: 'retardia',
    name: 'Retardia',
    description: 'A dangerous mountain with lava flows and rare minerals',
    svgpathid: 'retardia',
    theme: 'volcanic',
    biome: 'volcanic',
    difficulty: 7,
    locationType: 'REGION',
    hasMarket: false,
    hasMining: true,
    hasTravel: true,
    hasChat: true,
    chatScope: 'LOCAL',
    welcomeMessage: 'The heat is overwhelming, but the rewards are great.',
    lore: 'Ancient dwarves once mined here before the volcano awakened.',
  },
  // Ocean areas (for completeness but may not be interactive)
  {
    id: 'ocean-base',
    name: 'Ocean',
    description: 'The vast ocean surrounding the lands',
    svgpathid: 'oceanBase',
    theme: 'invisible',
    biome: 'ocean',
    difficulty: 0,
    locationType: 'REGION',
    hasMarket: false,
    hasMining: false,
    hasTravel: false,
    hasChat: false,
    chatScope: 'LOCAL',
    welcomeMessage: 'The endless blue stretches to the horizon.',
    lore: 'The ocean holds mysteries that few dare to explore.',
  },
] as const

// Item seed data
export const ITEM_SEED_DATA = [
  // Basic Materials
  {
    name: 'Dirty Coal',
    description: 'Basic fuel found in shallow mines',
    category: 'MATERIAL',
    rarity: 'COMMON',
  },
  {
    name: 'Iron Scraps',
    description: 'Rusty metal pieces, still useful',
    category: 'MATERIAL',
    rarity: 'COMMON',
  },
  {
    name: 'Ancient Coin',
    description: 'Currency from a forgotten civilization',
    category: 'MATERIAL',
    rarity: 'RARE',
  },
  {
    name: 'Crystal Shard',
    description: 'Glowing fragment with mysterious properties',
    category: 'MATERIAL',
    rarity: 'EPIC',
  },
  // Basic Equipment
  {
    name: 'Miners Hat',
    description: 'Worn leather hat with a dim headlamp',
    category: 'HAT',
    layerType: 'HAT',
    rarity: 'COMMON',
    durability: 100,
    energyEffect: 5,
  },
  {
    name: 'Work Gloves',
    description: 'Tough gloves for manual labor',
    category: 'CLOTHING',
    layerType: 'ACCESSORY',
    rarity: 'COMMON',
    durability: 80,
  },
  {
    name: 'Basic Pickaxe',
    description: 'Standard mining tool for beginners',
    category: 'TOOL',
    layerType: 'ACCESSORY',
    rarity: 'COMMON',
    durability: 50,
  },
  {
    name: 'Multi-Tool',
    description: 'Swiss army knife of the digital age',
    category: 'TOOL',
    layerType: 'ACCESSORY',
    rarity: 'COMMON',
    durability: 100,
  },
  // Consumables
  {
    name: 'Energy Drink',
    description: 'Restores energy and keeps you alert',
    category: 'CONSUMABLE',
    rarity: 'COMMON',
    energyEffect: 25,
  },
  {
    name: 'Health Potion',
    description: 'Mysterious red liquid that heals wounds',
    category: 'CONSUMABLE',
    rarity: 'UNCOMMON',
    healthEffect: 30,
  },
] as const

// Base market listings - what shops should stock initially
export const MARKET_SEED_DATA = {
  'Mining Plains': [
    { itemName: 'Miners Hat', quantity: 8, basePrice: 15 },
    { itemName: 'Basic Pickaxe', quantity: 5, basePrice: 20 },
    { itemName: 'Multi-Tool', quantity: 3, basePrice: 35 },
    { itemName: 'Energy Drink', quantity: 15, basePrice: 8 },
    { itemName: 'Work Gloves', quantity: 6, basePrice: 12 },
  ],
  'Crystal Caves': [
    { itemName: 'Energy Drink', quantity: 12, basePrice: 12 },
    { itemName: 'Health Potion', quantity: 8, basePrice: 28 },
    { itemName: 'Crystal Shard', quantity: 8, basePrice: 50 },
  ],
  'Frostpine Reaches': [
    { itemName: 'Energy Drink', quantity: 8, basePrice: 12 },
    { itemName: 'Health Potion', quantity: 6, basePrice: 28 },
    { itemName: 'Basic Pickaxe', quantity: 4, basePrice: 25 },
    { itemName: 'Work Gloves', quantity: 8, basePrice: 15 },
  ],
} as const

// Base mining resources - what can be mined where
export const MINING_SEED_DATA = {
  'Mining Plains': [
    { itemName: 'Dirty Coal', spawnRate: 0.5, maxPerDay: 25, difficulty: 1 },
    { itemName: 'Iron Scraps', spawnRate: 0.35, maxPerDay: 15, difficulty: 1 },
    { itemName: 'Basic Pickaxe', spawnRate: 0.08, maxPerDay: 3, difficulty: 1 },
  ],
  'Crystal Caves': [
    { itemName: 'Crystal Shard', spawnRate: 0.15, maxPerDay: 5, difficulty: 3 },
    { itemName: 'Ancient Coin', spawnRate: 0.08, maxPerDay: 3, difficulty: 2 },
  ],
  'Fungi Networks': [
    { itemName: 'Ancient Coin', spawnRate: 0.25, maxPerDay: 15, difficulty: 3 },
    { itemName: 'Crystal Shard', spawnRate: 0.12, maxPerDay: 6, difficulty: 3 },
  ],
} as const
